FROM microsoft/dotnet:sdk

WORKDIR /dotnetapp

RUN apt-get update

RUN apt-get install -y curl unzip

RUN curl -sSL https://aka.ms/getvsdbgsh | bash /dev/stdin -v latest -l ~/vsdbg

COPY ./src .

CD /dotnetapp/SNPN/

CMD /usr/bin/dotnet run watch
